### ISSUE TITLE
Support adding more than one version

### ISSUE THREAD

**Issue by bukinoshita** [bukinoshita/travis-init#2]
This our current [template](https://github.com/bukinoshita/travis-init/blob/master/lib/file-template.js). Before it returns the template it should verify if user passed more than 1 version, if so should return a the list of version like the example below

Example:

```
language: node_js
node_js:
  - "iojs"
  - "6"
```

**Comment by hptks** [comment]
Hey, I'd like to help with that issue :).

**Comment by bukinoshita** [comment]
Go for it @hptks! I'll be happy to see your pull request! Let me know if you have any questions about it. ☺️

**Comment by hptks** [comment]
Will sure do :)
